### ISSUE TITLE
Dub 1.5 / DMD 2.076

### ISSUE THREAD

**Issue by Wulfklaue** [dlang-snaps/dub.snap#4]
The snap is slightly out of date.

**Comment by WebDrake** [comment]
Yup, I will be updating next week some time. Apologies for the delay, it's a busy patch :-\

**Comment by WebDrake** [comment]
I've pushed an update.  The updated package should land in the `edge` channel some time in the next hours, if you would like to test it out, but I will aim to get it tested and into the stable release channel at some point in the next 2-3 days.

**Comment by WebDrake** [comment]
It's in the `edge` channel now: `sudo snap refresh --classic --edge dub` to try it out.

**Comment by WebDrake** [comment]
As of yesterday, 1.5.0 is in the `stable` release channel.
